name: lint_python
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    # strategy:
    #  matrix:
    #    os: [ubuntu-latest, macos-latest, windows-latest]
    #    python-version: [2.7, 3.5, 3.6, 3.7, 3.8]  # , pypy3]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
      - name: Install system dependencies
        run: |
          sudo apt-get install -y xvfb libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
      # with:
      #   python-version: ${{ matrix.python-version }}
      - run: pip install black codespell flake8 isort pytest
      - run: black --check . || true
      - run: codespell --quiet-level=2  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: isort --profile black . || true
      - run: pip install -r requirements.txt
      - run: xvfb-run pytest || true
